<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>My Worklist</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a9881f29-5b56-46ac-b83b-d5c64a0da405</testSuiteGuid>
   <testCaseLink>
      <guid>a280ae16-a22e-4cc7-9caa-8246271b1940</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Lead Status of Attempting contact</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>de24f6ea-c2d3-41ad-8f99-0811a45a3a6b</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/My Worklist Data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>de24f6ea-c2d3-41ad-8f99-0811a45a3a6b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>40198fec-6f8e-4900-9e4c-c513829dee70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>de24f6ea-c2d3-41ad-8f99-0811a45a3a6b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>8ba6a053-fd72-4ef3-bddf-ac70aabe8c81</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0414a207-1e82-476a-af3b-66a30c0b0fd7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Filter My Worklist</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4b8d86b3-2fae-4463-b6cb-64c6c1ba9db5</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/My Worklist Data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>4b8d86b3-2fae-4463-b6cb-64c6c1ba9db5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>13a6c55c-4580-4bd4-b732-f4f5618a01e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4b8d86b3-2fae-4463-b6cb-64c6c1ba9db5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>03ed95d6-5b3d-4caf-a714-2bcf462371de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4b8d86b3-2fae-4463-b6cb-64c6c1ba9db5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>statuses</value>
         <variableId>ef2ac103-f1a0-4a78-a2c1-27f2fc1cd86b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4b8d86b3-2fae-4463-b6cb-64c6c1ba9db5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>zip</value>
         <variableId>404cf399-d0e4-4bb8-a408-9ccfc3667438</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4b8d86b3-2fae-4463-b6cb-64c6c1ba9db5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>source</value>
         <variableId>b0002fad-49f9-4b5e-a52a-7d8b91c8f87e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4b8d86b3-2fae-4463-b6cb-64c6c1ba9db5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>state</value>
         <variableId>53aaaf0e-4cea-4357-985c-1f184b72ff91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9be9324d-70e9-4f06-ba59-c188a3bdb3b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/My Worklist - Coapplicant Basic</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9da95ff2-6653-4c93-8586-2cf1daea36b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>576ebb84-c67f-4fb0-929e-931499ff67dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9886a159-6f0f-43c9-ade0-f718ca12cd73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a75c5f6-1990-47e8-a5bc-80b760984e35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>695392c8-6676-4c73-96fb-8b2c74a92ab1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>390fee66-7000-44db-bd5a-c855b179e1f9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f118f24c-8a93-45a4-b11b-8c41bbb71eb2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/My Worklist - Coapplicant all fields</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>059a354f-5b9b-48c3-a1e5-c223147b0edc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebb6a38e-9173-4a8f-8318-08e148c97c80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fda8f8a4-5063-49f0-9d6b-c1e4bfaebe4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9883fc30-ba50-48a4-beb3-f5b0cf5ff998</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>731556fe-1842-49af-b27b-ba5c162993e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01f7f62b-35a2-4745-8cfc-15f00b000c01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6cc7a54f-64db-4c90-a1a2-0519832589be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Worklist - Budget</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27d02839-5234-4750-854c-9f9af1f82eab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15a7d2cc-f535-4822-87df-7527e77facf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb93fe03-3b2b-46e3-8e95-30bc14b0589b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1012988b-ab28-456a-b2bc-7c482b3f1a2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d538aa94-06ab-4157-9272-6ab3a491449b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b038e3df-fec9-4615-b332-019f4f4f5b14</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
