<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_UsernamePasswordLogin</name>
   <tag></tag>
   <elementGuidId>6e65df60-e567-44f4-bf61-51e015fc24c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.w-75.h-75.d-flex.flex-column.justify-content-center.ng-untouched.ng-pristine.ng-invalid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-75 h-75 d-flex flex-column justify-content-center ng-untouched ng-pristine ng-invalid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UsernamePasswordLogin</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[1]/app-login[1]/div[@class=&quot;d-flex flex-column align-items-center&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;d-flex justify-content-center align-items-center&quot;]/form[@class=&quot;w-75 h-75 d-flex flex-column justify-content-center ng-untouched ng-pristine ng-invalid&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'UsernamePasswordLogin' or . = 'UsernamePasswordLogin')]</value>
   </webElementXpaths>
</WebElementEntity>
