<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DOB (ex. 06211970)_form-control shadow-none ng-pristine ng-valid flatpickr-input ng-touched active</name>
   <tag></tag>
   <elementGuidId>106cecf1-8a40-4a6b-97f0-9372050d11ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @placeholder = 'Select date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.shadow-none.ng-pristine.ng-valid.flatpickr-input.ng-touched.active</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@formcontrolname = 'dob' and @type = 'text' and @placeholder = 'Select date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>dob</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control shadow-none ng-pristine ng-valid flatpickr-input ng-touched active</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select date</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;d-flex flex-column ng-star-inserted&quot;]/div[@class=&quot;menuShow&quot;]/div[@class=&quot;w-100 d-flex flex-column&quot;]/div[@class=&quot;w-auto&quot;]/app-community-leads-details[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;d-flex h-100&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;container-fluid shadow h-auto w-100&quot;]/app-coapliccant[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;d-flex flex-column w-100&quot;]/div[2]/div[@class=&quot;container-fluid&quot;]/form[@class=&quot;container row ng-pristine ng-valid ng-touched&quot;]/div[@class=&quot;form-group col-4&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control shadow-none ng-pristine ng-valid flatpickr-input ng-touched active&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Select date']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[21]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
